title: A+B problem
author: 
- anomyous
date: 2022-01-08 14:40:00
license:
  code: AGPL
  docs: CC BY-SA 4.0
type: output only
catagory: None
tags:
  default:
    - None
time_limit: 1s
memory_limit: 128MB
